name = "ballerz-graph"
main = "src/index.ts"
compatibility_date = "2024-12-04"

[[kv_namespaces]]
binding = "BALLER" # Matches the script's KVNamespace
id = "ec2bd233d0b14daaa6fa8b9b9df285b0"
preview_id = "84a56abe24d84240847cb57cd4e3a2fa"

[observability.logs]
enabled = true
